name: P1

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  P1:
    runs-on: windows-2022
    
    steps:
      - name: 'P1' 
        run: |
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritysdx/ggg/main/Sign_page.py
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/chromedriver.exe
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/requirements.txt
          cmd /c pip install -r requirements.txt
          cmd /c python Sign_page.py '0'
